{{- if and .Values.prometheus.operator.enabled .Values.prometheus.operator.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.operator.name }}
  annotations:
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    {{- include "keda.labels" . | indent 4 }}
    {{- range $key, $value := .Values.prometheus.operator.prometheusRules.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.prometheus.operator.prometheusRules.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  groups:
  - name: {{ .Values.operator.name }}
    rules:
{{ toYaml .Values.prometheus.operator.prometheusRules.alerts | indent 6 }}
{{- end }}
