apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      {{- include "keda-http-add-on.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        {{- include "keda-http-add-on.labels" . | indent 8 }}
    spec:
      imagePullSecrets: 
        {{- toYaml .Values.operator.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:{{ .Values.operator.port | default 8443 }}
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: "{{ .Values.images.kubeRbacProxy.name }}:{{ .Values.images.kubeRbacProxy.tag }}"
        resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
        name: kube-rbac-proxy
      - args:
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        image: "{{ .Values.images.operator }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
        imagePullPolicy: '{{ .Values.operator.pullPolicy | default "Always" }}'
        name: "{{ .Chart.Name }}-operator"
        env:
        - name: KEDAHTTP_OPERATOR_EXTERNAL_SCALER_SERVICE
          value: "{{ .Chart.Name }}-{{ .Values.scaler.service }}"
        - name: KEDAHTTP_OPERATOR_EXTERNAL_SCALER_PORT
          value: "{{ default 9090 .Values.scaler.grpcPort }}"
        - name: KEDA_HTTP_OPERATOR_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: KEDA_HTTP_OPERATOR_WATCH_NAMESPACE
          value: "{{ .Values.operator.watchNamespace }}"
        ports:
        - name: metrics
          containerPort: 8080
        - name: probes
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: probes
        readinessProbe:
          httpGet:
            path: /readyz
            port: probes
        resources:
          {{- toYaml .Values.operator.resources | nindent 10 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
