apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
    keda.sh/addon: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-controller-manager
    {{- include "keda-addons-http.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
      keda.sh/addon: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
        keda.sh/addon: {{ .Chart.Name }}
        app: {{ .Chart.Name }}
        name: {{ .Chart.Name }}-operator
        {{- include "keda-addons-http.labels" . | indent 8 }}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:{{ .Values.operator.port | default 8443 }}
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        image: "{{ .Values.images.operator }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.operator.pullPolicy | default "Always" }}
        name: {{ .Chart.Name }}-operator
        env:
        - name: KEDAHTTP_OPERATOR_EXTERNAL_SCALER_IMAGE
          value: "{{ .Values.images.scaler }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
        - name: KEDAHTTP_OPERATOR_INTERCEPTOR_IMAGE
          value: "{{ .Values.images.interceptor }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
        - name: INTERCEPTOR_PULL_POLICY
          value: {{ .Values.operator.pullPolicy | default "Always" }}
        - name: SCALER_PULL_POLICY
          value: {{ .Values.operator.pullPolicy | default "Always"}}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
