apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: scaler
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-external-scaler
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: scaler
      {{- include "keda-http-add-on.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scaler
        {{- include "keda-http-add-on.labels" . | indent 8 }}
    spec:
      imagePullSecrets: 
        {{- toYaml .Values.scaler.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Chart.Name }}-external-scaler
      containers:
      - args:
        image: "{{ .Values.images.scaler }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.scaler.pullPolicy | default "Always" }}
        name: "{{ .Chart.Name }}-external-scaler"
        ports:
        - containerPort: {{ .Values.scaler.healthPort }}
          name: scaler-health
        - containerPort: {{ .Values.scaler.grpcPort }}
          name: scaler-grpc
        env:
        - name: KEDA_HTTP_SCALER_TARGET_ADMIN_DEPLOYMENT
          value: "{{ .Chart.Name }}-interceptor"
        - name: KEDA_HTTP_SCALER_PORT
          value: "{{ .Values.scaler.grpcPort }}"
        - name: KEDA_HTTP_HEALTH_PORT
          value: "{{ .Values.scaler.healthPort }}"
        - name: KEDA_HTTP_SCALER_TARGET_ADMIN_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: KEDA_HTTP_SCALER_TARGET_ADMIN_SERVICE
          value: "{{ .Chart.Name }}-{{ .Values.interceptor.admin.service }}"
        - name: KEDA_HTTP_SCALER_TARGET_ADMIN_PORT
          value: "{{ default 9091 .Values.interceptor.admin.port }}"
        - name: KEDA_HTTP_SCALER_STREAM_INTERVAL_MS
          value: "{{ .Values.scaler.streamInterval }}"
        resources:
          {{- toYaml .Values.scaler.resources | nindent 10 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.scaler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scaler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scaler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
