apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: scaler
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: "{{ .Chart.Name }}-{{ .Values.scaler.service }}"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ default 9090 .Values.scaler.grpcPort }}
    targetPort: grpc
  selector:
    app.kubernetes.io/component: scaler
    {{- include "keda-http-add-on.labels" . | indent 4 }}
