apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-scaler-azure-cosmos-db.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        {{- include "external-scaler-azure-cosmos-db.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: scaler-grpc
              containerPort: 4050
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
      terminationGracePeriodSeconds: 10
