name: Helm Chart CI (Azure Cosmos DB add-on)

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/ci-azure-cosmos-db-add-on.yml
      - azure-cosmos-db-add-on/**
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/ci-azure-cosmos-db-add-on.yml
      - azure-cosmos-db-add-on/**

jobs:
  verify-helm-chart:
    name: Verify Helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1

      - name: Lint 'Azure Cosmos DB add-on' Helm chart
        run: helm lint ./azure-cosmos-db-add-on/ --strict

      - name: Show 'Azure Cosmos DB add-on' Helm chart template
        run: helm template test-release ./azure-cosmos-db-add-on/ --namespace test-namespace

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Install 'Azure Cosmos DB add-on' chart
        run: helm install test-release ./azure-cosmos-db-add-on/ --namespace test-namespace --create-namespace --wait --timeout=2m

      - name: Get 'Azure Cosmos DB add-on' service
        run: kubectl get service keda-add-ons-azure-cosmos-db --namespace=test-namespace

      - name: Get 'Azure Cosmos DB add-on' deployment
        run: kubectl get deployment keda-add-ons-azure-cosmos-db --namespace=test-namespace

      - name: Uninstall 'Azure Cosmos DB add-on' Helm chart
        run: helm uninstall test-release --namespace test-namespace
