name: Helm Chart CI (HTTP add-on)
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-http-add-on.yml'
      - 'http-add-on/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-http-add-on.yml'
      - 'http-add-on/**'

jobs:
  lint-helm-3-x:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Helm install
      uses: Azure/setup-helm@v1

    - name: Lint 'http-add-on' Helm chart
      run: helm lint http-add-on

  deploy-helm-3-x:
    name: Deploy to Kubernetes ${{ matrix.kubernetesVersion }}
    needs: lint-helm-3-x
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [v1.24, v1.22, v1.21, v1.20, v1.19, v1.18, v1.17]
        include:
          # Images are defined on every Kind release
          # See https://github.com/kubernetes-sigs/kind/releases
        - kubernetesVersion: v1.24
          kindImage: kindest/node:v1.24.0@sha256:406fd86d48eaf4c04c7280cd1d2ca1d61e7d0d61ddef0125cb097bc7b82ed6a1
        - kubernetesVersion: v1.23
          kindImage: kindest/node:v1.23.6@sha256:1af0f1bee4c3c0fe9b07de5e5d3fafeb2eec7b4e1b268ae89fcab96ec67e8355
        - kubernetesVersion: v1.22
          kindImage: kindest/node:v1.22.9@sha256:6e57a6b0c493c7d7183a1151acff0bfa44bf37eb668826bf00da5637c55b6d5e
        - kubernetesVersion: v1.21
          kindImage: kindest/node:v1.21.12@sha256:ae05d44cc636ee961068399ea5123ae421790f472c309900c151a44ee35c3e3e
        - kubernetesVersion: v1.20
          kindImage: kindest/node:v1.20.15@sha256:a6ce604504db064c5e25921c6c0fffea64507109a1f2a512b1b562ac37d652f3
        - kubernetesVersion: v1.19
          kindImage: kindest/node:v1.19.16@sha256:dec41184d10deca01a08ea548197b77dc99eeacb56ff3e371af3193c86ca99f4
        - kubernetesVersion: v1.18
          kindImage: kindest/node:v1.18.20@sha256:38a8726ece5d7867fb0ede63d718d27ce2d41af519ce68be5ae7fcca563537ed
        - kubernetesVersion: v1.17
          kindImage: kindest/node:v1.17.17@sha256:66f1d0d91a88b8a001811e2f1054af60eef3b669a9a74f9b6db871f2f1eeed00
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Helm install
      uses: Azure/setup-helm@v1

    - name: Create k8s ${{ matrix.kubernetesVersion }} Kind Cluster
      uses: helm/kind-action@v1.2.0
      with:
        version: v1.13.0
        node_image: ${{ matrix.kindImage }}

    - name: Show Kubernetes version
      run: |
        kubectl version

    - name: Show Kubernetes nodes
      run: |
        kubectl get nodes -o wide

    - name: Show Helm version
      run: |
        helm version

    - name: Create KEDA namespace
      run: kubectl create ns keda

    - name: Install KEDA chart
      run: helm install keda ./keda/ --namespace keda

    - name: Template Helm chart
      run: helm template http-add-on ./http-add-on/ --namespace keda

    - name: Install Helm chart
      run: helm install http-add-on ./http-add-on/ --namespace keda

    - name: Show Kubernetes resources
      run: kubectl get all --namespace keda
      if: always()

    - name: Get all HTTPScaledObjects
      run: kubectl get httpscaledobjects

    - name: Get all CRDs
      run: kubectl get crds

    - name: Get HTTPScaledObject CRD
      run: kubectl get crds/httpscaledobjects.http.keda.sh

    - name: Describe HTTPScaledObject CRD
      run: kubectl describe crds/httpscaledobjects.http.keda.sh
